FROM golang:1.19 AS builder

WORKDIR /app
COPY . .

RUN cd /app/src  && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app .
CMD ["./src/main"]